In [100]:
from google.colab import files
uploaded = files.upload()

import pandas as pd
df = pd.read_csv('dataset.csv')
df.head()

Saving dataset.csv to dataset (2).csv

   Serial No          Name Roll No  Age    Phone No      Place
0          1  Aarav Sharma    R001   20  9876543210      Delhi
1          2  Vivaan Gupta    R002   21  9876543211     Mumbai
2          3  Aditya Singh    R003   19  9876543212  Bangalore
3          4   Arjun Verma    R004   22  9876543213    Chennai
4          5  Ananya Patel    R005   20  9876543214    Kolkata

In [101]:
import pandas as pd
df = pd.read_csv('/dataset.csv')
df.head(100)

    Serial No             Name Roll No  Age    Phone No       Place
0           1     Aarav Sharma    R001   20  9876543210       Delhi
1           2     Vivaan Gupta    R002   21  9876543211      Mumbai
2           3     Aditya Singh    R003   19  9876543212   Bangalore
3           4      Arjun Verma    R004   22  9876543213     Chennai
4           5     Ananya Patel    R005   20  9876543214     Kolkata
..        ...              ...     ...  ...         ...         ...
95         96  Priyanshi Joshi    R096   23  9876543305   Ahmedabad
96         97      Arnav Mehta    R097   18  9876543306       Surat
97         98    Kanika Kapoor    R098   21  9876543307      Bhopal
98         99      Dhruv Yadav    R099   24  9876543308       Patna
99        100    Shruti Sharma    R100   22  9876543309  Chandigarh

[100 rows x 6 columns]

In [102]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Serial No  100 non-null    int64
 1   Name       100 non-null    object
 2   Roll No    100 non-null    object
 3   Age        100 non-null    int64
 4   Phone No   100 non-null    int64
 5   Place      100 non-null    object
dtypes: int64(3), object(3)
memory usage: 4.8+ KB

In [103]:
df = pd.read_csv('/DataBook1.csv')
df.head(20)

    Unnamed: 0           Name Roll No   Age    Phone No      Place
0            1   Aarav Sharma    R001  20.0  9876543210      Delhi
1            2   Vivaan Gupta    R002  21.0  9876543211     Mumbai
2            3   Aditya Singh    R003  19.0  9876543212  Bangalore
3            4    Arjun Verma    R004  22.0  9876543213        NaN
4            5   Ananya Patel    R005  20.0  9876543214    Kolkata
5            6     Diya Joshi    R006  23.0  9876543215  Hyderabad
6            7   Ishita Mehta    R007  18.0  9876543216       Pune
7            8   Priya Kapoor    R008  21.0  9876543217     Jaipur
8            9            NaN    R009  24.0  9876543218    Lucknow
9           10   Sneha Sharma    R010  22.0  9876543219  Rishikesh
10          11    Rohan Gupta    R011  20.0  9876543220      Delhi
11          12    Kavya Singh    R012  21.0  9876543221     Mumbai
12          13     Amit Verma    R013   NaN  9876543222  Bangalore
13          14    Pooja Patel    R014  22.0  9876543223    Chennai
14          15   Nikhil Joshi    R015  20.0  9876543224    Kolkata
15          16     Neha Mehta    R016  23.0  9876543225  Hyderabad
16          17   Karan Kapoor    R017  18.0  9876543226       Pune
17          18     Riya Yadav    R018  21.0  9876543227     Jaipur
18          19  Manish Sharma    R019  24.0  9876543228    Lucknow
19          20    Tanya Gupta    R020  22.0  9876543229  Rishikesh

In [104]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  20 non-null     int64
 1   Name        19 non-null     object
 2   Roll No     20 non-null     object
 3   Age         19 non-null     float64
 4   Phone No    20 non-null     int64
 5   Place       19 non-null     object
dtypes: float64(1), int64(2), object(3)
memory usage: 1.1+ KB

In [105]:
df.fillna('null')

    Unnamed: 0           Name Roll No   Age    Phone No      Place
0            1   Aarav Sharma    R001  20.0  9876543210      Delhi
1            2   Vivaan Gupta    R002  21.0  9876543211     Mumbai
2            3   Aditya Singh    R003  19.0  9876543212  Bangalore
3            4    Arjun Verma    R004  22.0  9876543213       null
4            5   Ananya Patel    R005  20.0  9876543214    Kolkata
5            6     Diya Joshi    R006  23.0  9876543215  Hyderabad
6            7   Ishita Mehta    R007  18.0  9876543216       Pune
7            8   Priya Kapoor    R008  21.0  9876543217     Jaipur
8            9           null    R009  24.0  9876543218    Lucknow
9           10   Sneha Sharma    R010  22.0  9876543219  Rishikesh
10          11    Rohan Gupta    R011  20.0  9876543220      Delhi
11          12    Kavya Singh    R012  21.0  9876543221     Mumbai
12          13     Amit Verma    R013  null  9876543222  Bangalore
13          14    Pooja Patel    R014  22.0  9876543223    Chennai
14          15   Nikhil Joshi    R015  20.0  9876543224    Kolkata
15          16     Neha Mehta    R016  23.0  9876543225  Hyderabad
16          17   Karan Kapoor    R017  18.0  9876543226       Pune
17          18     Riya Yadav    R018  21.0  9876543227     Jaipur
18          19  Manish Sharma    R019  24.0  9876543228    Lucknow
19          20    Tanya Gupta    R020  22.0  9876543229  Rishikesh

In [106]:
df.fillna('0')

    Unnamed: 0           Name Roll No   Age    Phone No      Place
0            1   Aarav Sharma    R001  20.0  9876543210      Delhi
1            2   Vivaan Gupta    R002  21.0  9876543211     Mumbai
2            3   Aditya Singh    R003  19.0  9876543212  Bangalore
3            4    Arjun Verma    R004  22.0  9876543213          0
4            5   Ananya Patel    R005  20.0  9876543214    Kolkata
5            6     Diya Joshi    R006  23.0  9876543215  Hyderabad
6            7   Ishita Mehta    R007  18.0  9876543216       Pune
7            8   Priya Kapoor    R008  21.0  9876543217     Jaipur
8            9              0    R009  24.0  9876543218    Lucknow
9           10   Sneha Sharma    R010  22.0  9876543219  Rishikesh
10          11    Rohan Gupta    R011  20.0  9876543220      Delhi
11          12    Kavya Singh    R012  21.0  9876543221     Mumbai
12          13     Amit Verma    R013     0  9876543222  Bangalore
13          14    Pooja Patel    R014  22.0  9876543223    Chennai
14          15   Nikhil Joshi    R015  20.0  9876543224    Kolkata
15          16     Neha Mehta    R016  23.0  9876543225  Hyderabad
16          17   Karan Kapoor    R017  18.0  9876543226       Pune
17          18     Riya Yadav    R018  21.0  9876543227     Jaipur
18          19  Manish Sharma    R019  24.0  9876543228    Lucknow
19          20    Tanya Gupta    R020  22.0  9876543229  Rishikesh

In [107]:
print(df[df['Age'] > 20])

    Unnamed: 0           Name Roll No   Age    Phone No      Place
1            2   Vivaan Gupta    R002  21.0  9876543211     Mumbai
3            4    Arjun Verma    R004  22.0  9876543213        NaN
5            6     Diya Joshi    R006  23.0  9876543215  Hyderabad
7            8   Priya Kapoor    R008  21.0  9876543217     Jaipur
8            9            NaN    R009  24.0  9876543218    Lucknow
9           10   Sneha Sharma    R010  22.0  9876543219  Rishikesh
11          12    Kavya Singh    R012  21.0  9876543221     Mumbai
13          14    Pooja Patel    R014  22.0  9876543223    Chennai
15          16     Neha Mehta    R016  23.0  9876543225  Hyderabad
17          18     Riya Yadav    R018  21.0  9876543227     Jaipur
18          19  Manish Sharma    R019  24.0  9876543228    Lucknow
19          20    Tanya Gupta    R020  22.0  9876543229  Rishikesh

In [108]:
print(df['Age'] > 20)

0     False
1      True
2     False
3      True
4     False
5      True
6     False
7      True
8      True
9      True
10    False
11     True
12    False
13     True
14    False
15     True
16    False
17     True
18     True
19     True
Name: Age, dtype: bool

In [109]:
if(df['Age'] > 20).any:
  print(df)

    Unnamed: 0           Name Roll No   Age    Phone No      Place
0            1   Aarav Sharma    R001  20.0  9876543210      Delhi
1            2   Vivaan Gupta    R002  21.0  9876543211     Mumbai
2            3   Aditya Singh    R003  19.0  9876543212  Bangalore
3            4    Arjun Verma    R004  22.0  9876543213        NaN
4            5   Ananya Patel    R005  20.0  9876543214    Kolkata
5            6     Diya Joshi    R006  23.0  9876543215  Hyderabad
6            7   Ishita Mehta    R007  18.0  9876543216       Pune
7            8   Priya Kapoor    R008  21.0  9876543217     Jaipur
8            9            NaN    R009  24.0  9876543218    Lucknow
9           10   Sneha Sharma    R010  22.0  9876543219  Rishikesh
10          11    Rohan Gupta    R011  20.0  9876543220      Delhi
11          12    Kavya Singh    R012  21.0  9876543221     Mumbai
12          13     Amit Verma    R013   NaN  9876543222  Bangalore
13          14    Pooja Patel    R014  22.0  9876543223    Chennai
14          15   Nikhil Joshi    R015  20.0  9876543224    Kolkata
15          16     Neha Mehta    R016  23.0  9876543225  Hyderabad
16          17   Karan Kapoor    R017  18.0  9876543226       Pune
17          18     Riya Yadav    R018  21.0  9876543227     Jaipur
18          19  Manish Sharma    R019  24.0  9876543228    Lucknow
19          20    Tanya Gupta    R020  22.0  9876543229  Rishikesh

In [110]:
df['Nationality'] = 'Indian'
df.head(20)

    Unnamed: 0           Name Roll No   Age    Phone No      Place Nationality
0            1   Aarav Sharma    R001  20.0  9876543210      Delhi      Indian
1            2   Vivaan Gupta    R002  21.0  9876543211     Mumbai      Indian
2            3   Aditya Singh    R003  19.0  9876543212  Bangalore      Indian
3            4    Arjun Verma    R004  22.0  9876543213        NaN      Indian
4            5   Ananya Patel    R005  20.0  9876543214    Kolkata      Indian
5            6     Diya Joshi    R006  23.0  9876543215  Hyderabad      Indian
6            7   Ishita Mehta    R007  18.0  9876543216       Pune      Indian
7            8   Priya Kapoor    R008  21.0  9876543217     Jaipur      Indian
8            9            NaN    R009  24.0  9876543218    Lucknow      Indian
9           10   Sneha Sharma    R010  22.0  9876543219  Rishikesh      Indian
10          11    Rohan Gupta    R011  20.0  9876543220      Delhi      Indian
11          12    Kavya Singh    R012  21.0  9876543221     Mumbai      Indian
12          13     Amit Verma    R013   NaN  9876543222  Bangalore      Indian
13          14    Pooja Patel    R014  22.0  9876543223    Chennai      Indian
14          15   Nikhil Joshi    R015  20.0  9876543224    Kolkata      Indian
15          16     Neha Mehta    R016  23.0  9876543225  Hyderabad      Indian
16          17   Karan Kapoor    R017  18.0  9876543226       Pune      Indian
17          18     Riya Yadav    R018  21.0  9876543227     Jaipur      Indian
18          19  Manish Sharma    R019  24.0  9876543228    Lucknow      Indian
19          20    Tanya Gupta    R020  22.0  9876543229  Rishikesh      Indian

In [111]:
df.drop('Roll No',axis=1,inplace=True)
df.head(20)

    Unnamed: 0           Name   Age    Phone No      Place Nationality
0            1   Aarav Sharma  20.0  9876543210      Delhi      Indian
1            2   Vivaan Gupta  21.0  9876543211     Mumbai      Indian
2            3   Aditya Singh  19.0  9876543212  Bangalore      Indian
3            4    Arjun Verma  22.0  9876543213        NaN      Indian
4            5   Ananya Patel  20.0  9876543214    Kolkata      Indian
5            6     Diya Joshi  23.0  9876543215  Hyderabad      Indian
6            7   Ishita Mehta  18.0  9876543216       Pune      Indian
7            8   Priya Kapoor  21.0  9876543217     Jaipur      Indian
8            9            NaN  24.0  9876543218    Lucknow      Indian
9           10   Sneha Sharma  22.0  9876543219  Rishikesh      Indian
10          11    Rohan Gupta  20.0  9876543220      Delhi      Indian
11          12    Kavya Singh  21.0  9876543221     Mumbai      Indian
12          13     Amit Verma   NaN  9876543222  Bangalore      Indian
13          14    Pooja Patel  22.0  9876543223    Chennai      Indian
14          15   Nikhil Joshi  20.0  9876543224    Kolkata      Indian
15          16     Neha Mehta  23.0  9876543225  Hyderabad      Indian
16          17   Karan Kapoor  18.0  9876543226       Pune      Indian
17          18     Riya Yadav  21.0  9876543227     Jaipur      Indian
18          19  Manish Sharma  24.0  9876543228    Lucknow      Indian
19          20    Tanya Gupta  22.0  9876543229  Rishikesh      Indian

In [112]:
df.groupby('Place')['Age'].mean()

Place
Bangalore    19.0
Chennai      22.0
Delhi        20.0
Hyderabad    23.0
Jaipur       21.0
Kolkata      20.0
Lucknow      24.0
Mumbai       21.0
Pune         18.0
Rishikesh    22.0
Name: Age, dtype: float64

In [113]:
df.groupby('Place')['Age'].sum()

Place
Bangalore    19.0
Chennai      22.0
Delhi        40.0
Hyderabad    46.0
Jaipur       42.0
Kolkata      40.0
Lucknow      48.0
Mumbai       42.0
Pune         36.0
Rishikesh    44.0
Name: Age, dtype: float64

In [114]:
import pandas as pd

In [115]:
data = [100,200,300,400]
base = pd.Series(data)
print(base)

0    100
1    200
2    300
3    400
dtype: int64

In [116]:
user_dict = {'Name': ['Alice','Bob','Charlie'],'Age':[25,30,35]}
df = pd.DataFrame(user_dict)
print(df)

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

In [117]:
df = pd.read_csv('/dataset.csv')

In [118]:
df.head(5)

   Serial No          Name Roll No  Age    Phone No      Place
0          1  Aarav Sharma    R001   20  9876543210      Delhi
1          2  Vivaan Gupta    R002   21  9876543211     Mumbai
2          3  Aditya Singh    R003   19  9876543212  Bangalore
3          4   Arjun Verma    R004   22  9876543213    Chennai
4          5  Ananya Patel    R005   20  9876543214    Kolkata

In [119]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Serial No  100 non-null    int64
 1   Name       100 non-null    object
 2   Roll No    100 non-null    object
 3   Age        100 non-null    int64
 4   Phone No   100 non-null    int64
 5   Place      100 non-null    object
dtypes: int64(3), object(3)
memory usage: 4.8+ KB

In [120]:
print(df.shape)

(100, 6)

In [121]:
df = pd.DataFrame({'Product':['A','B','C'],'Price':[10,20,30],'Quantity':[4,2,5]})
print(df['Price'])

0    10
1    20
2    30
Name: Price, dtype: int64

In [122]:
df = pd.DataFrame({'Salary':[15000,20000,89000,12000,7000,34000,64000]})
print(df[df['Salary'] > 50000])

   Salary
2   89000
6   64000

In [123]:
print(df.min())

Salary    7000
dtype: int64

In [124]:
print(df.max())

Salary    89000
dtype: int64

In [125]:
print(df.mean())

Salary    34428.571429
dtype: float64

In [126]:
print(df.std())

Salary    30805.070702
dtype: float64

In [127]:
clean_df.to_csv('output.csv', index=False)

In [128]:
df = pd.read_csv('/DataBook1.csv')

In [130]:
df.drop([4, 9, 13])

    Unnamed: 0           Name Roll No   Age    Phone No      Place
0            1   Aarav Sharma    R001  20.0  9876543210      Delhi
1            2   Vivaan Gupta    R002  21.0  9876543211     Mumbai
2            3   Aditya Singh    R003  19.0  9876543212  Bangalore
3            4    Arjun Verma    R004  22.0  9876543213        NaN
5            6     Diya Joshi    R006  23.0  9876543215  Hyderabad
6            7   Ishita Mehta    R007  18.0  9876543216       Pune
7            8   Priya Kapoor    R008  21.0  9876543217     Jaipur
8            9            NaN    R009  24.0  9876543218    Lucknow
10          11    Rohan Gupta    R011  20.0  9876543220      Delhi
11          12    Kavya Singh    R012  21.0  9876543221     Mumbai
12          13     Amit Verma    R013   NaN  9876543222  Bangalore
14          15   Nikhil Joshi    R015  20.0  9876543224    Kolkata
15          16     Neha Mehta    R016  23.0  9876543225  Hyderabad
16          17   Karan Kapoor    R017  18.0  9876543226       Pune
17          18     Riya Yadav    R018  21.0  9876543227     Jaipur
18          19  Manish Sharma    R019  24.0  9876543228    Lucknow
19          20    Tanya Gupta    R020  22.0  9876543229  Rishikesh

In [139]:
df.fillna(df.mean(numeric_only=True), inplace=True)
print(df)

    Unnamed: 0           Name Roll No        Age    Phone No      Place
0            1   Aarav Sharma    R001  20.000000  9876543210      Delhi
1            2   Vivaan Gupta    R002  21.000000  9876543211     Mumbai
2            3   Aditya Singh    R003  19.000000  9876543212  Bangalore
3            4    Arjun Verma    R004  22.000000  9876543213        NaN
4            5   Ananya Patel    R005  20.000000  9876543214    Kolkata
5            6     Diya Joshi    R006  23.000000  9876543215  Hyderabad
6            7   Ishita Mehta    R007  18.000000  9876543216       Pune
7            8   Priya Kapoor    R008  21.000000  9876543217     Jaipur
8            9            NaN    R009  24.000000  9876543218    Lucknow
9           10   Sneha Sharma    R010  22.000000  9876543219  Rishikesh
10          11    Rohan Gupta    R011  20.000000  9876543220      Delhi
11          12    Kavya Singh    R012  21.000000  9876543221     Mumbai
12          13     Amit Verma    R013  21.105263  9876543222  Bangalore
13          14    Pooja Patel    R014  22.000000  9876543223    Chennai
14          15   Nikhil Joshi    R015  20.000000  9876543224    Kolkata
15          16     Neha Mehta    R016  23.000000  9876543225  Hyderabad
16          17   Karan Kapoor    R017  18.000000  9876543226       Pune
17          18     Riya Yadav    R018  21.000000  9876543227     Jaipur
18          19  Manish Sharma    R019  24.000000  9876543228    Lucknow
19          20    Tanya Gupta    R020  22.000000  9876543229  Rishikesh

In [141]:
df_employees = pd.DataFrame({'emp_ID':['CS1','CS2','CS3'],'Names':['Roy','Rex','Jack']})
df_salaries = pd.DataFrame({'emp_ID':['CS1','CS2','CS3'],'Salary':[10000,20000,30000]})
df_merged = pd.merge(df_employees,df_salaries,on='emp_ID')
print(df_merged)

  emp_ID Names  Salary
0    CS1   Roy   10000
1    CS2   Rex   20000
2    CS3  Jack   30000

In [142]:
df = pd.DataFrame({'Final_Score':[70,47,61,30,90,88,50,100]})
df['Grade'] = pd.cut(df['Final_Score'],bins=[0,40,60,80,100],labels=['D','C','B','A'])
print(df)

   Final_Score Grade
0           70     B
1           47     C
2           61     B
3           30     D
4           90     A
5           88     A
6           50     C
7          100     A

In [143]:
df = pd.DataFrame({'Final_Score':[70,47,61,30,90,88,50,100]})
df['Status'] = pd.cut(df['Final_Score'],bins=[0,50,100],labels=['Fail','Pass'])
print(df)

   Final_Score Status
0           70   Pass
1           47   Fail
2           61   Pass
3           30   Fail
4           90   Pass
5           88   Pass
6           50   Fail
7          100   Pass

In [144]:
df = pd.DataFrame({'emp_ID':['CS1','CS2','CS3'],'Names':['Roy','Rex','Jack']})
df_new = df.T
print(df_new)

          0    1     2
emp_ID  CS1  CS2   CS3
Names   Roy  Rex  Jack

In [146]:
df_org = df_new.T
print(df_org)

  emp_ID Names
0    CS1   Roy
1    CS2   Rex
2    CS3  Jack

In [149]:
import scipy.optimize as opt

In [150]:
import scipy.constants as const
pi_value = const.pi
speed_of_light = const.c
planck_constant = const.h
print(pi_value)
print(speed_of_light)
print(planck_constant)

3.141592653589793
299792458.0
6.62607015e-34

In [151]:
import scipy.constants as const
milles = 55
pounds = 10
meter = milles * const.mile
kg = pounds * const.pound
print(meter)
print(kg)

88513.91999999998
4.5359237

In [152]:
import scipy.special as sp
arr = [1,8,27,64]
cube_root = sp.cbrt(arr)
print(cube_root)

[1. 2. 3. 4.]

In [153]:
import scipy.stats as st
dataset = [1,2,2,3,4,4,4,5,6]
m = st.mode(dataset)
print(m)

ModeResult(mode=np.int64(4), count=np.int64(3))

In [155]:
import scipy.stats as st
arr = [2,8,32]
gm = st.gmean(arr)
print(gm)

7.999999999999998

In [157]:
import scipy.linalg as sl
matrix = [[4,5],[2,3]]
determinant = sl.det(matrix)
print(determinant)

2.0000000000000018

In [158]:
import numpy as np
import scipy.linalg as sl
M = np.array([[1,2],[3,4]])
inverse = sl.inv(M)
print(inverse)

[[-2.   1. ]
 [ 1.5 -0.5]]

In [160]:
import pandas as pd
import scipy.stats as st
df = pd.DataFrame({'Final_Score':[70,47,61,30,90,88,50,100]})
above_75 = st.percentileofscore(df['Final_Score'],75)
print(above_75)

62.5

In [161]:
st.zscore(df['Final_Score'])

array([ 0.13152709, -0.87684726, -0.26305418, -1.62216744,  1.00837435,
        0.92068963, -0.74532017,  1.44679799])

In [165]:
from scipy.optimize import minimize_scalar
import numpy as np

def f(x):
  return x**2 + 10 * np.sin(x)

print(f(4))

8.431975046920718

SyntaxError: invalid syntax (651564826.py, line 1)